server: 
  port: 8200 
  
logging-level:
    root: DEBUG
    
spring: 
  cloud: 
    stream: 
      bindings: 
        input: 
          destination: comments.chat  
          group: cpdlog-comments-chat 
          content-type: application/json 
        newComments: 
          destination: cpdlog-comments-chat2
          group: comments.chat 
          content-type: application/json 
        clientToBroker: 
          destination: cpdlog-chat-user-messages 
          group: app-chatMessages 
        brokerToClient: 
          destination: cpdlog-chat-user-messages 
          group: topic-chatMessages
